# Plugins
plugins:
  - jekyll-feed

# Theme
remote_theme: daattali/beautiful-jekyll@5.0.0

# Basic site
title: Kapil Easwar
description: Insert fun personal tagline here.



# Feed generation options
feed:
  path: /blog/feed.xml

